export const loginInputs = [
  {
    id: 1,
    name: "email",
    keyboardType: "email",
    placeholder: "Enter Your Email Address",
    styles: "",
    title: "Email Address",
    secure: false,
    value: "",
  },
  {
    id: 2,
    name: "password",
    keyboardType: "password",
    placeholder: "Enter Your Password",
    styles: "",
    title: "Password",
    secure: true,
    value: "",
  },
];

export const registerInputs = [
  {
    id: 1,
    name: "firstName",
    keyboardType: "default",
    placeholder: "First Name",
    styles: "",
    title: "First Name",
    secure: false,
    value: "",
  },
  {
    id: 2,
    name: "lastName",
    keyboardType: "default",
    placeholder: "Last Name",
    styles: "",
    title: "Last Name",
    secure: false,
    value: "",
  },
  {
    id: 3,
    name: "phone",
    keyboardType: "number-pad",
    placeholder: "Enter Your Phone Number",
    styles: "",
    title: "Phone Number",
    secure: false,
    value: "",
  },
  {
    id: 4,
    name: "email",
    keyboardType: "email",
    placeholder: "Enter Your Email Address",
    styles: "",
    title: "Email Address",
    secure: false,
    value: "",
  },
  {
    id: 5,
    name: "password",
    keyboardType: "password",
    placeholder: "Enter Your Password",
    styles: "",
    title: "Password",
    secure: true,
    value: "",
  },
  {
    id: 6,
    name: "confirmPassword",
    keyboardType: "password",
    placeholder: "Confirm Password",
    styles: "",
    title: "Confirm Password",
    secure: true,
    value: "",
  },
  {
    id: 7,
    name: "addressOne",
    keyboardType: "default",
    placeholder: "Address 1",
    styles: "",
    title: "Address 1",
    secure: false,
    value: "",
  },
  {
    id: 8,
    name: "addressTwo",
    keyboardType: "default",
    placeholder: "Address 2",
    styles: "",
    title: "Address 2",
    secure: false,
    value: "",
  },
];
